import { logger } from "./logger";

/**
 * Call the LLM with a prompt and return the raw string response.
 * Currently a mock — replace with OpenAI / Azure OpenAI integration.
 */
export async function callLLM(prompt: string): Promise<string> {
  logger.debug(`LLM prompt (${prompt.length} chars)`);

  // TODO: Replace this mock with a real LLM API call
  logger.info("LLM: returning mock response (replace with real integration)");

  // Detect which kind of prompt this is and return appropriate mock JSON
  // Check planning prompt first (more specific match)
  if (prompt.includes("user stories and tasks") || prompt.includes("agile project manager")) {
    return JSON.stringify({
      stories: [
        {
          title: "User authentication via social login",
          description: "Allow users to sign in using Google and Apple accounts",
          acceptanceCriteria: [
            "User can sign in with Google",
            "User can sign in with Apple",
            "Auth token is stored securely",
          ],
          tasks: [
            {
              title: "Integrate Google Sign-In SDK",
              description: "Add and configure Google Sign-In package for Flutter",
              estimateHours: 4,
            },
            {
              title: "Integrate Apple Sign-In SDK",
              description: "Add and configure Apple Sign-In package for Flutter",
              estimateHours: 4,
            },
            {
              title: "Implement auth token storage",
              description: "Store authentication tokens securely using flutter_secure_storage",
              estimateHours: 3,
            },
          ],
        },
        {
          title: "Social login UI screens",
          description: "Create login screens with social provider buttons and error handling",
          acceptanceCriteria: [
            "Login screen displays Google and Apple buttons",
            "Loading indicator shown during authentication",
            "Error messages displayed on failure",
          ],
          tasks: [
            {
              title: "Design login screen layout",
              description: "Create responsive login screen with social login buttons",
              estimateHours: 3,
            },
            {
              title: "Implement loading and error states",
              description: "Add loading spinner and error snackbar to login flow",
              estimateHours: 2,
            },
            {
              title: "Write widget tests for login screen",
              description: "Create widget tests covering success, loading, and error states",
              estimateHours: 3,
            },
          ],
        },
      ],
    });
  }

  // Requirement prompt
  if (prompt.includes("requirements analyst") || prompt.includes("structured requirement")) {
    return JSON.stringify({
      title: "Mock Requirement",
      description: "This is a mock requirement generated by the LLM.",
      businessRules: ["Rule 1", "Rule 2"],
      acceptanceCriteria: ["Criteria 1", "Criteria 2"],
      affectedModules: ["Module A"],
    });
  }

  // Architecture prompt
  if (prompt.includes("software architect") || prompt.includes("define the architecture")) {
    return JSON.stringify({
      newModules: ["auth"],
      newFiles: [
        "lib/auth/domain/entities/user.dart",
        "lib/auth/domain/repositories/auth_repository.dart",
        "lib/auth/domain/usecases/sign_in_with_google.dart",
        "lib/auth/domain/usecases/sign_in_with_apple.dart",
        "lib/auth/data/repositories/auth_repository_impl.dart",
        "lib/auth/data/datasources/auth_remote_datasource.dart",
        "lib/auth/presentation/pages/login_page.dart",
        "lib/auth/presentation/bloc/auth_bloc.dart",
        "lib/auth/presentation/bloc/auth_event.dart",
        "lib/auth/presentation/bloc/auth_state.dart",
      ],
      updatedFiles: [
        "lib/main.dart",
        "lib/routes.dart",
        "pubspec.yaml",
      ],
      layers: ["domain", "data", "presentation"],
    });
  }

  return JSON.stringify({ message: "LLM mock response" });
}