import fs from "node:fs/promises";
import path from "node:path";
import { logger } from "../utils/logger";
import type { Architecture } from "../models/architecture.model";
import type { CodeAnalysis } from "../models/codeAnalysis.model";

// ── Helpers ─────────────────────────────────────────────────────

/** Convert snake_case feature name to PascalCase */
function toPascal(name: string): string {
  return name
    .split(/[_\-\s]+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
}

/** Write a file only if it does not already exist */
async function writeIfNew(
  filePath: string,
  content: string,
  projectPath: string,
  createdFiles: string[]
): Promise<void> {
  try {
    await fs.access(filePath);
    logger.info(`Dev Agent: skipped (exists) ${filePath}`);
    return;
  } catch {
    // does not exist — proceed
  }

  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, content, "utf-8");
  createdFiles.push(path.relative(projectPath, filePath).replace(/\\/g, "/"));
  logger.info(`Dev Agent: created ${filePath}`);
}

// ── Flutter scaffolding ─────────────────────────────────────────

async function scaffoldFlutter(
  projectPath: string,
  featureName: string,
  architecture: Architecture
): Promise<string[]> {
  const name = featureName.toLowerCase();
  const pascal = toPascal(featureName);
  const featureDir = path.join(projectPath, "lib", "features", name);
  const createdFiles: string[] = [];

  const files: { rel: string; content: string }[] = [
    {
      rel: `data/${name}_service.dart`,
      content: `// Auto-generated by AI Software Factory\n\nclass ${pascal}Service {\n  // TODO: implement\n}\n`,
    },
    {
      rel: `data/${name}_repository.dart`,
      content: `// Auto-generated by AI Software Factory\n\nclass ${pascal}Repository {\n  // TODO: implement\n}\n`,
    },
    {
      rel: `domain/${name}_usecase.dart`,
      content: `// Auto-generated by AI Software Factory\n\nclass ${pascal}Usecase {\n  // TODO: implement\n}\n`,
    },
    {
      rel: `domain/${name}_model.dart`,
      content: `// Auto-generated by AI Software Factory\n\nclass ${pascal}Model {\n  // TODO: implement\n}\n`,
    },
    {
      rel: `presentation/${name}_page.dart`,
      content: `// Auto-generated by AI Software Factory\n\nimport 'package:flutter/material.dart';\n\nclass ${pascal}Page extends StatelessWidget {\n  const ${pascal}Page({super.key});\n\n  @override\n  Widget build(BuildContext context) {\n    return const Scaffold(\n      body: Center(child: Text('${pascal}Page')),\n    );\n  }\n}\n`,
    },
    {
      rel: `presentation/${name}_controller.dart`,
      content: `// Auto-generated by AI Software Factory\n\nclass ${pascal}Controller {\n  // TODO: implement\n}\n`,
    },
  ];

  // Create layer directories
  for (const layer of ["data", "domain", "presentation"]) {
    await fs.mkdir(path.join(featureDir, layer), { recursive: true });
  }

  // Write feature files
  for (const f of files) {
    await writeIfNew(path.join(featureDir, f.rel), f.content, projectPath, createdFiles);
  }

  // Also create any extra files from architecture.newFiles
  for (const relFile of architecture.newFiles) {
    const filePath = path.join(projectPath, relFile);
    const content = `// ${relFile}\n// Auto-generated by AI Software Factory\n\n// TODO: implement\n`;
    await writeIfNew(filePath, content, projectPath, createdFiles);
  }

  return createdFiles;
}

// ── .NET / C# scaffolding ───────────────────────────────────────

async function scaffoldDotnet(
  projectPath: string,
  featureName: string,
  architecture: Architecture
): Promise<string[]> {
  const pascal = toPascal(featureName);
  const createdFiles: string[] = [];

  const folders = [
    "Application/Services",
    "Application/DTOs",
    "Domain/Entities",
    "Domain/Interfaces",
    "Infrastructure/Repositories",
    "API/Controllers",
  ];

  // Ensure all directories exist
  for (const folder of folders) {
    await fs.mkdir(path.join(projectPath, folder), { recursive: true });
  }

  const files: { rel: string; content: string }[] = [
    {
      rel: `API/Controllers/${pascal}Controller.cs`,
      content: [
        "using Microsoft.AspNetCore.Mvc;",
        "",
        `namespace API.Controllers;`,
        "",
        `[ApiController]`,
        `[Route("api/[controller]")]`,
        `public class ${pascal}Controller : ControllerBase`,
        `{`,
        `    // TODO: implement`,
        `}`,
        "",
      ].join("\n"),
    },
    {
      rel: `Domain/Interfaces/I${pascal}Service.cs`,
      content: [
        `namespace Domain.Interfaces;`,
        "",
        `public interface I${pascal}Service`,
        `{`,
        `    // TODO: define contract`,
        `}`,
        "",
      ].join("\n"),
    },
    {
      rel: `Application/Services/${pascal}Service.cs`,
      content: [
        `using Domain.Interfaces;`,
        "",
        `namespace Application.Services;`,
        "",
        `public class ${pascal}Service : I${pascal}Service`,
        `{`,
        `    // TODO: implement`,
        `}`,
        "",
      ].join("\n"),
    },
    {
      rel: `Domain/Interfaces/I${pascal}Repository.cs`,
      content: [
        `namespace Domain.Interfaces;`,
        "",
        `public interface I${pascal}Repository`,
        `{`,
        `    // TODO: define contract`,
        `}`,
        "",
      ].join("\n"),
    },
    {
      rel: `Infrastructure/Repositories/${pascal}Repository.cs`,
      content: [
        `using Domain.Interfaces;`,
        "",
        `namespace Infrastructure.Repositories;`,
        "",
        `public class ${pascal}Repository : I${pascal}Repository`,
        `{`,
        `    // TODO: implement`,
        `}`,
        "",
      ].join("\n"),
    },
    {
      rel: `Application/DTOs/${pascal}Dto.cs`,
      content: [
        `namespace Application.DTOs;`,
        "",
        `public class ${pascal}Dto`,
        `{`,
        `    // TODO: define properties`,
        `}`,
        "",
      ].join("\n"),
    },
    {
      rel: `Domain/Entities/${pascal}.cs`,
      content: [
        `namespace Domain.Entities;`,
        "",
        `public class ${pascal}`,
        `{`,
        `    // TODO: define entity properties`,
        `}`,
        "",
      ].join("\n"),
    },
  ];

  // Write feature files
  for (const f of files) {
    await writeIfNew(path.join(projectPath, f.rel), f.content, projectPath, createdFiles);
  }

  // Also create any extra files from architecture.newFiles
  for (const relFile of architecture.newFiles) {
    const filePath = path.join(projectPath, relFile);
    const content = `// ${relFile}\n// Auto-generated by AI Software Factory\n\n// TODO: implement\n`;
    await writeIfNew(filePath, content, projectPath, createdFiles);
  }

  return createdFiles;
}

// ── Public entry point ──────────────────────────────────────────

/**
 * Dev Agent: scaffolds feature folder structure based on project type.
 * Supports Flutter (Dart) and C# (.NET) projects.
 * Does NOT overwrite existing files.
 */
export async function devAgent(
  architecture: Architecture,
  projectPath: string,
  featureName: string,
  codeAnalysis: CodeAnalysis
): Promise<string[]> {
  const projectType = codeAnalysis.projectType;
  logger.info(`Dev Agent: scaffolding "${featureName}" for ${projectType} project`);

  const createdFiles =
    projectType === "dotnet"
      ? await scaffoldDotnet(projectPath, featureName, architecture)
      : await scaffoldFlutter(projectPath, featureName, architecture);

  logger.info(`Dev Agent: scaffolding complete — ${createdFiles.length} files created`);
  return createdFiles;
}
