import fs from "node:fs/promises";
import path from "node:path";
import { logger } from "../utils/logger";
import { loadArtifact, saveArtifact } from "../services/artifact.service";
import type { PlanningOutput } from "../models/story.model";
import type { TestPlan } from "../models/testCase.model";

/**
 * Test Agent: generates test case descriptions for every task
 * in the planning output, and optionally scaffolds placeholder
 * Dart test files in the target project.
 */
export async function testAgent(
  planning: PlanningOutput,
  projectPath: string,
  featureName: string
): Promise<TestPlan[]> {
  // Try cached artifact first
  const cached = await loadArtifact(projectPath, featureName, "tests");
  if (cached) {
    logger.info("Test Agent: using cached artifact");
    return cached as TestPlan[];
  }

  logger.info("Test Agent: generating test cases from planning output...");

  const testPlans: TestPlan[] = [];

  for (const story of planning.stories) {
    if (!story.tasks || story.tasks.length === 0) {
      logger.info(`Test Agent: story "${story.title}" has no tasks, skipping`);
      continue;
    }

    for (const task of story.tasks) {
      const plan: TestPlan = {
        story: story.title,
        task: task.title,
        tests: [
          {
            title: `should ${task.title.toLowerCase()}`,
            description: `Verify that: ${task.description}`,
          },
        ],
      };
      testPlans.push(plan);
    }
  }

  // Validate every task has at least one test
  const totalTests = testPlans.reduce((sum, p) => sum + p.tests.length, 0);
  if (totalTests === 0) {
    throw new Error("Test Agent: no test cases generated (planning has no tasks)");
  }

  logger.info(`Test Agent: ${testPlans.length} task test plans, ${totalTests} total test cases`);

  // Scaffold placeholder Dart test files
  await scaffoldTestFiles(testPlans, projectPath, featureName);

  // Save artifact
  await saveArtifact(projectPath, featureName, "tests", testPlans);

  return testPlans;
}

/**
 * Create placeholder Dart test files inside the target project.
 * Files are placed in: test/features/[feature_name]/
 * Does NOT overwrite existing files.
 */
async function scaffoldTestFiles(
  testPlans: TestPlan[],
  projectPath: string,
  featureName: string
): Promise<void> {
  const testDir = path.join(projectPath, "test", "features", featureName.toLowerCase());
  await fs.mkdir(testDir, { recursive: true });

  for (const plan of testPlans) {
    // Derive a file name from the task title
    const slug = plan.task
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "_")
      .replace(/^_|_$/g, "");
    const fileName = `${slug}_test.dart`;
    const filePath = path.join(testDir, fileName);

    // Do not overwrite existing files
    try {
      await fs.access(filePath);
      logger.info(`Test Agent: skipped (exists) ${filePath}`);
      continue;
    } catch {
      // File does not exist — create it
    }

    const testMethods = plan.tests
      .map(
        (tc) =>
          `    test('${tc.title}', () {\n      // ${tc.description}\n      // TODO: implement\n    });`
      )
      .join("\n\n");

    const content = `// Auto-generated by AI Software Factory
// Story: ${plan.story}
// Task: ${plan.task}

import 'package:flutter_test/flutter_test.dart';

void main() {
  group('${plan.task}', () {
${testMethods}
  });
}
`;

    await fs.writeFile(filePath, content, "utf-8");
    logger.info(`Test Agent: created ${filePath}`);
  }
}
